apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    component: jenkins-master
  name: jenkins
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jenkins-master
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jenkins
        component: jenkins-master
    spec:
      containers:
      - image: registry.cn-beijing.aliyuncs.com/acs-sample/jenkins-master-serverless:2.156
        imagePullPolicy: Always
        name: jenkins
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 50000
          name: slavelistener
          protocol: TCP
        resources: {}
        #volumeMounts:
        #  - mountPath: /var/jenkins_home
        #    name: jenkins-home
      #volumes:
      #  - name: jenkins-home
      #    nfs:
      #      path: /
      #      server:
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
    component: jenkins-master
  name: jenkins
spec:
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: jenkins-master
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
    component: jenkins-master
  name: jenkins-agent
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
spec:
  ports:
  - name: slavelistener
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    component: jenkins-master
  type: LoadBalancer
