apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: jenkins-master
  name: jenkins
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jenkins-master
  template:
    metadata:
      labels:
        app: jenkins
        component: jenkins-master
    spec:
      containers:
      - image: jenkins/jenkins:2.319.1-lts-jdk11
        imagePullPolicy: Always
        name: jenkins
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 50000
          name: slavelistener
          protocol: TCP
        resources: {}
        #volumeMounts:
        #  - mountPath: /var/jenkins_home
        #    name: jenkins-home
      #volumes:
      #  - name: jenkins-home
      #    nfs:
      #      path: /
      #      server:
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
    component: jenkins-master
  name: jenkins
spec:
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: jenkins-master
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
    component: jenkins-master
  name: jenkins-agent
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
spec:
  ports:
  - name: slavelistener
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    component: jenkins-master
  type: LoadBalancer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: ack-jenkins-sa
  name: ack-jenkins-sa-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: ack-jenkins-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ack-jenkins-sa
  name: ack-jenkins-sa
  namespace: default
