apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
    component: jenkins-master
  name: jenkins-agent
  annotations:
    service.beta.kubernetes.io/alicloud-loadbalancer-address-type: intranet
spec:
  ports:
  - name: slavelistener
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    component: jenkins-master
  type: LoadBalancer
