apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
    component: jenkins-master
  name: jenkins
spec:
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: jenkins-master
  type: LoadBalancer
